check if the current user is the root user

diff --git a/solo b/solo
--- a/solo
+++ b/solo
@@ -1,3 +1,6 @@
 #!/usr/bin/env bash
 
-echo "Hello World"
+if [ ${UID} == 0 ]; then
+    echo 'You cannot run Solo as the root user' >&2
+    exit 1
+fi
